service: supplier-service

plugins:
  - serverless-bundle
  - serverless-domain-manager

provider: ${file(../../serverless.common.yml):provider}

functions:
  get:
    handler: handler.main
    events:
      - http: GET /

custom:
  customDomain: ${file(../../serverless.common.yml):custom.customDomain}
