service: supplier-service

frameworkVersion: '^2.27.0'


plugins:
  - serverless-bundle
  - serverless-domain-manager
  - serverless-offline-ssm-provider
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-2
  stage: ${opt:stage, 'dev'}
  memorySize: 128
  apiGateway:
    shouldStartNameWithService: true
  tracing:
    apiGateway: true
    lambda: true

functions:
  healthcheck:
    handler: src/healthcheck.main
    events:
      - http: GET /healthcheck

custom:
  serverless-offline-ssm-provider:
    file: .ssm
  customDomain:
    domainName: ${ssm:/plannerax/${self:provider.stage}/DOMAIN}
    basePath: 'supplier'
    stage: ${self:provider.stage}
    createRoute53Record: true
